## --------------------
## DON'T EDIT THIS FILE
## --------------------
## Engine: yamlinc@0.1.10
## Source: ./app/docs/swagger/include.yaml

openapi: 3.0.1
info:
  title: Ravn challenge V2 Rony Garcia
  description: This is de API documentation for the Ravn challenge.
paths:
  /api/v1/login:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description: Token and refresh token to access the system
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
        '400':
          description: >-
            Bad Request. The request could not be understood by the server due
            to malformed syntax. The client should not repeat the request
            without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
                Invalid credentials:
                  value:
                    message: Invalid credentials
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
    area: api
  /api/v1/logout:
    post:
      tags:
        - auth
      responses:
        '200':
          description: Token and refresh token to access the system
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
    area: api
  /api/v1/signup:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                confirm_password:
                  type: string
        required: true
      responses:
        '200':
          description: User object created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
        '400':
          description: >-
            Bad Request. The request could not be understood by the server due
            to malformed syntax. The client should not repeat the request
            without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
                email taken:
                  value:
                    message: This email has been taken
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
    area: api
  '/api/v1/user/confirm/{token}':
    get:
      parameters:
        - in: path
          name: token
          required: true
          type: string
          description: Token to validate user and confirm
      tags:
        - auth
      responses:
        '200':
          description: User object created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User has been confirmed successfully
        '400':
          description: >-
            Bad Request. The request could not be understood by the server due
            to malformed syntax. The client should not repeat the request
            without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Token not valid:
                  value:
                    message: Token not valid
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
    area: api
  /api/v1/user/recovery/password:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
        required: true
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email has been sent
        '400':
          description: >-
            Bad Request. The request could not be understood by the server due
            to malformed syntax. The client should not repeat the request
            without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
    area: api
  /api/v1/user/change/password:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                confirm_password:
                  type: string
        required: true
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Updated password
        '400':
          description: >-
            Bad Request. The request could not be understood by the server due
            to malformed syntax. The client should not repeat the request
            without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
    area: api
  /api/v1/products:
    get:
      parameters:
        - in: query
          name: page
          required: true
          type: integer
          description: number page
        - in: query
          name: per_page
          required: true
          type: integer
          description: quantity per
        - in: query
          name: page
          required: true
          type: integer
          description: number page
        - in: query
          name: pagination
          required: false
          type: string
          description: Parameter to deactivate pagination
        - in: query
          name: category_id
          required: true
          type: integer
          description: Parameter to filter by categories
      tags:
        - products
      responses:
        '200':
          description: List of products available in the store to be sold.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
                    quantity:
                      type: integer
                    active:
                      type: boolean
                    category_id:
                      type: integer
                    ProductImages:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          path:
                            type: string
                          product_id:
                            type: integer
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.. Since
            the visitor failed to provide valid credentials, access has been
            denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.. This
            error occurs when you try to access a page or network resource that
            you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '422':
          description: >-
            Unprocessable entity.The request could not be understood by the
            server due to malformed syntax. The client should not repeat the
            request without modifications..The request could not be understood
            by the server due to malformed syntax. The client should not repeat
            the request without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Page:
                  value:
                    message: per_page must be a number
                Per Page:
                  value:
                    message: per_page must be a number
                User id:
                  value:
                    message: The category_id must be a number
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond..
            This happen when the network resource you are addressing encountered
            a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
    post:
      tags:
        - products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                quantity:
                  type: integer
                category_id:
                  type: integer
        required: true
      responses:
        '201':
          description: Product successfully created with its corresponding properties.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
                    quantity:
                      type: integer
                    active:
                      type: boolean
                    category_id:
                      type: integer
        '400':
          description: >-
            Bad Request. The request could not be understood by the server due
            to malformed syntax. The client should not repeat the request
            without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Denied access:
                  value:
                    message: Denied access
        '404':
          description: Not found. Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Not found:
                  value:
                    message: Category not found
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
  '/api/v1/products/{product_id}':
    parameters:
      - in: path
        name: product_id
        required: true
        type: integer
        description: product id to show details
    get:
      tags:
        - products
      responses:
        '200':
          description: The product details have been successfully obtained.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  price:
                    type: number
                  quantity:
                    type: integer
                  active:
                    type: boolean
                  category_id:
                    type: integer
                  ProductImages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        path:
                          type: string
                        product_id:
                          type: integer'
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '422':
          description: >-
            Unprocessable entity.The request could not be understood by the
            server due to malformed syntax. The client should not repeat the
            request without modifications..The request could not be understood
            by the server due to malformed syntax. The client should not repeat
            the request without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                params product id:
                  value:
                    message: The parameter must be a number
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
    put:
      tags:
        - products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                quantity:
                  type: integer
                category_id:
                  type: integer
        required: true
      responses:
        '200':
          description: Product properties updated successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
                    quantity:
                      type: integer
                    category_id:
                      type: integer
        '400':
          description: >-
            Bad Request.The request could not be understood by the server due to
            malformed syntax. The client should not repeat the request without
            modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Picture required:
                  value:
                    message: Picture is required
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
    delete:
      tags:
        - products
      responses:
        '200':
          description: Product deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product has been deleted successfully
        '400':
          description: >-
            Bad Request.The request could not be understood by the server due to
            malformed syntax. The client should not repeat the request without
            modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Product associated:
                  value:
                    message: >-
                      Is not possible to delete this product, because it´s
                      associated to an order
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
    patch:
      tags:
        - products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                active:
                  type: boolean
        required: true
      responses:
        '200':
          description: Changing product availability to be sold.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: The product has been enabled successfully
        '400':
          description: >-
            Bad Request.The request could not be understood by the server due to
            malformed syntax. The client should not repeat the request without
            modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '404':
          description: Not found. Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Not found:
                  value:
                    message: Product not found
        '422':
          description: >-
            Unprocessable entity.The request could not be understood by the
            server due to malformed syntax. The client should not repeat the
            request without modifications..The request could not be understood
            by the server due to malformed syntax. The client should not repeat
            the request without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                params product id:
                  value:
                    message: The parameter must be a number
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
  '/api/v1/products/{product_id}/image':
    parameters:
      - in: path
        name: product_id
        required: true
        type: integer
        description: product id
    put:
      tags:
        - products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                picture:
                  type: string
        required: true
      responses:
        '200':
          description: Updating the product image to be sold.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Image saved succesfully
        '400':
          description: >-
            Bad Request.The request could not be understood by the server due to
            malformed syntax. The client should not repeat the request without
            modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Picture required:
                  value:
                    message: Picture is required
                Max quantity picture reached:
                  value:
                    message: cannot upload more pictures
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '404':
          description: Not found. Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Not found:
                  value:
                    message: Product not found
        '422':
          description: >-
            Unprocessable entity.The request could not be understood by the
            server due to malformed syntax. The client should not repeat the
            request without modifications..The request could not be understood
            by the server due to malformed syntax. The client should not repeat
            the request without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                params product id:
                  value:
                    message: The parameter must be a number
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
    area: api
  '/api/v1/products/{product_id}/cart':
    parameters:
      - in: path
        name: product_id
        required: true
        type: integer
        description: product id
    post:
      tags:
        - products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
        required: true
      responses:
        '200':
          description: Product added to cart successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product added to cart
        '400':
          description: >-
            Bad Request.The request could not be understood by the server due to
            malformed syntax. The client should not repeat the request without
            modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
                Wrong quantity:
                  value:
                    message: Cannot add more than
                Already added:
                  value:
                    message: Product is already added
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
    delete:
      tags:
        - products
      responses:
        '200':
          description: Product removed to cart successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product was removed
        '400':
          description: >-
            Bad Request.The request could not be understood by the server due to
            malformed syntax. The client should not repeat the request without
            modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Cart empty:
                  value:
                    message: There is nothing to remove
                Product is not in the cart:
                  value:
                    message: The product is not in the cart
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
  '/api/v1/products/{product_id}/reaction':
    parameters:
      - in: path
        name: product_id
        required: true
        type: integer
        description: Adding reactions to the product according to its id
    post:
      tags:
        - products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reaction_type_id:
                  type: integer
        required: true
      responses:
        '200':
          description: No message result
          content: null
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '404':
          description: Not found. Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Product Not found:
                  value:
                    message: Product not found
                Reaction type not found:
                  value:
                    message: Reaction type not found
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
  '/api/v1/products/{product_image_id}/image':
    parameters:
      - in: path
        name: product_image_id
        required: true
        type: integer
        description: Getting the product image according to its id
    get:
      tags:
        - products
      responses:
        '200':
          description: Product picture got successfully
          content:
            image/*:
              schema:
                type: string
                format: binary
        '404':
          description: Not found. Resource not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Image not found:
                  value:
                    message: Image not found
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
  /api/v1/orders:
    get:
      parameters:
        - in: query
          name: page
          required: true
          type: integer
          description: number page
        - in: query
          name: per_page
          required: true
          type: integer
          description: quantity per
        - in: query
          name: page
          required: true
          type: integer
          description: number page
        - in: query
          name: pagination
          required: false
          type: string
          description: Parameter to deactivate pagination
        - in: query
          name: user_id
          required: true
          type: integer
          description: Parameter to filter by if when the logged user is manager
      tags:
        - orders
      responses:
        '200':
          description: >-
            List of orders, if user is MANAGER, the endpoint will return all
            orders, if the user is CLIENT will return only its orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    order_date:
                      type: string
                      format: date
                    total:
                      type: number
                    user_id:
                      type: integer
                    address:
                      type: string
                    phone:
                      type: string
                    status_id:
                      type: integer
                    OrderDetail:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          product_id:
                            type: integer
                          order_id:
                            type: integer
                          quantity:
                            type: integer
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.. Since
            the visitor failed to provide valid credentials, access has been
            denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.. This
            error occurs when you try to access a page or network resource that
            you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Forbidden:
                  value:
                    message: Denied access
        '422':
          description: >-
            Unprocessable entity.The request could not be understood by the
            server due to malformed syntax. The client should not repeat the
            request without modifications..The request could not be understood
            by the server due to malformed syntax. The client should not repeat
            the request without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Page:
                  value:
                    message: per_page must be a number
                Per Page:
                  value:
                    message: per_page must be a number
                User id:
                  value:
                    message: The user_id must be a number
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond..
            This happen when the network resource you are addressing encountered
            a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
    post:
      tags:
        - orders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                phone:
                  type: string
        required: true
      responses:
        '200':
          description: Successful order creation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  order_date:
                    type: string
                    format: date
                  total:
                    type: number
                  user_id:
                    type: integer
                  address:
                    type: string
                  phone:
                    type: string
                  status_id:
                    type: integer
                  OrderDetail:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        product_id:
                          type: integer
                        order_id:
                          type: integer
                        quantity:
                          type: integer
        '400':
          description: >-
            Bad Request.The request could not be understood by the server due to
            malformed syntax. The client should not repeat the request without
            modifications..The request could not be understood by the server due
            to malformed syntax. The client should not repeat the request
            without modifications.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Cart empty:
                  value:
                    message: The cart is empty
                Wrong body request:
                  value:
                    message: Wrong body request
                    fields:
                      message: property is required
                      field: property
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.. Since
            the visitor failed to provide valid credentials, access has been
            denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.. This
            error occurs when you try to access a page or network resource that
            you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Denied access:
                  value:
                    message: Denied access
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond..
            This happen when the network resource you are addressing encountered
            a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
  '/api/v1/orders/{order_id}':
    get:
      parameters:
        - in: path
          name: order_id
          required: true
          type: integer
          description: order id
      tags:
        - orders
      responses:
        '200':
          description: >-
            Order details obtained with your properties successfully according
            to its id.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  order_date:
                    type: string
                    format: date
                  total:
                    type: number
                  user_id:
                    type: integer
                  address:
                    type: string
                  phone:
                    type: string
                  status_id:
                    type: integer
                  OrderDetail:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        product_id:
                          type: integer
                        order_id:
                          type: integer
                        quantity:
                          type: integer
                        products:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              price:
                                type: number
                              quantity:
                                type: integer
                              active:
                                type: boolean
                              category_id:
                                type: integer
                              ProductImages:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: integer
                                    path:
                                      type: string
                                    product_id:
                                      type: integer
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.. Since
            the visitor failed to provide valid credentials, access has been
            denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.. This
            error occurs when you try to access a page or network resource that
            you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Denied access:
                  value:
                    message: Denied access
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond..
            This happen when the network resource you are addressing encountered
            a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
  '/api/v1/orders/{order_id}/payment':
    post:
      parameters:
        - in: path
          name: order_id
          required: true
          type: integer
          description: Order made payment validation.
      tags:
        - orders
      responses:
        '200':
          description: The payment of the order has been made successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Order successfully paid
        '401':
          description: >-
            Unauthorized. Since the visitor failed to provide valid credentials,
            access has been denied, and the error page has been loaded.. Since
            the visitor failed to provide valid credentials, access has been
            denied, and the error page has been loaded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    message: Unauthorized
        '403':
          description: >-
            Not Found. This error occurs when you try to access a page or
            network resource that you do not have a permission to access.. This
            error occurs when you try to access a page or network resource that
            you do not have a permission to access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Denied access:
                  value:
                    message: Denied access
        '500':
          description: >-
            Internal Server Error. This happen when the network resource you are
            addressing encountered a problem and the server can not respond..
            This happen when the network resource you are addressing encountered
            a problem and the server can not respond.
          content: null
      x-codegen-request-body-name: body
      area: api
components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
        fields:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              field:
                type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
